apiVersion: v1
kind: Secret
metadata:
  name: github-token
  namespace: argocd
type: Opaque
stringData:
  token: #token
  # Create a GitHub Personal Access Token with 'repo' scope
  # https://github.com/settings/tokens/new?scopes=repo&description=ArgoCD%20PR%20Generator
